repos:
-   repo: local
    hooks:
    -   id: check-sql
        name: Validate SQL statements
        entry: python -m tests.check_sql_statements
        language: system
        pass_filenames: false
-   repo: local
    hooks:
    -   id: init_py_files
        name: __init__.py files
        entry: python tests/build-init-files.py -v --root .
        language: system
        pass_filenames: false
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black
        language: system
        require_serial: true
        types_or: [python, pyi]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: mixed-line-ending
        args: ["--fix=lf"]
    -   id: end-of-file-fixer
        exclude: ".*?(.hex|.clsp|.clvm|.clib)"
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: check-ast
    -   id: debug-statements
-   repo: local
    hooks:
    -   id: clvm_hex
        name: .clsp.hex files
        entry: python tools/manage_clvm.py check
        language: system
        pass_filenames: false
-   repo: local
    hooks:
    -   id: chialispp
        name: Pretty print chialisp files
        entry: python tools/chialispp.py .
        language: system
        pass_filenames: false
-   repo: local
    hooks:
    -   id: build mypy.ini
        name: build mypy.ini
        entry: python manage-mypy.py build-mypy-ini
        language: system
        pass_filenames: false
-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: mypy
        language: system
        pass_filenames: false
-   repo: local
    hooks:
    -   id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
-   repo: local
    hooks:
    -   id: flake8
        name: Flake8
        entry: flake8
        language: system
        types: [python]
